### ISSUE TITLE
a minor typo

### ISSUE THREAD

**Issue by snail59** [RedHat-EMEA-SSA-Team/hetzner-ocp4#114]
The file ansible/roles/openshift-4-cluster/tasks/post-install.yml reads "identity_roviders" a few times.
I think the intended name was "identity_providers" ( with a "p").

> grep -R _rovider ansible
ansible/roles/openshift-4-cluster/tasks/post-install.yml:    identity_roviders: "[]"
ansible/roles/openshift-4-cluster/tasks/post-install.yml:        identity_roviders: "{{ identity_roviders }} + [ {{ htpasswd_idp }} ]"
ansible/roles/openshift-4-cluster/tasks/post-install.yml:    - name: Push redhatsso_idp to identity_roviders
ansible/roles/openshift-4-cluster/tasks/post-install.yml:        identity_roviders: "{{ identity_roviders }} + [ {{ redhatsso_idp }} ]"
ansible/roles/openshift-4-cluster/tasks/post-install.yml:    - name: Push github_idp to identity_roviders
ansible/roles/openshift-4-cluster/tasks/post-install.yml:        identity_roviders: "{{ identity_roviders }} + [ {{ github_idp }} ]"
ansible/roles/openshift-4-cluster/tasks/post-install.yml:          identityProviders: "{{ identity_roviders }}"

Greetings

**Comment by rbo** [comment]
Merged into dev.
