### ISSUE TITLE
New screen shot for rebooting server

### ISSUE THREAD

**Issue by rh-tmichels** [RedHat-EMEA-SSA-Team/hetzner-ocp4#115]
![Reset](https://user-images.githubusercontent.com/50710587/87309535-08c3e200-c51d-11ea-821e-3fa755a06b19.png)

... as Hetzner has updated the page.

**Comment by rbo** [comment]
Still the same for me:

![Screenshot 2020-07-30 at 20 17 51](https://user-images.githubusercontent.com/36604/88959189-e6162500-d2a1-11ea-8c5e-c66e184f0c89.png)
