### ISSUE TITLE
Systemd reload

### ISSUE THREAD

**Issue by Sifa171** [RedHat-EMEA-SSA-Team/hetzner-ocp4#120]
RHEL8

Before enabling and starting the loadbalancer systemd service you have to do a 'systemctl daemon-reload' otherwise the playbook fails.

**Comment by rbo** [comment]
I never had this problem on RHEL 8. Only if you change a systemd file you have to reload. What is the exactly error message?

**Comment by rbo** [comment]
I had the problem... And fixed in devel branch: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/commit/0df95b6a2783af20c406af9d9377a39a9de03a49
