### ISSUE TITLE
Should use cloudflare_account_api_token in Let'sEncrypt DNS Rules

### ISSUE THREAD

**Issue by weizenberg** [RedHat-EMEA-SSA-Team/hetzner-ocp4#123]
After following the Readme I configured the cluster.yml with `cloudflare_account_api_token` and `cloudflare_account_email`. However, the Let'sEncyrpt task got failed because it's trying to use `le_letsencrypt_account_email` and `le_cloudflare_account_api_token` instead. For allowing consistency, I recommend changing this to the `cloudflare_account_api_token` and `cloudflare_account_email` values.

The following places should be updated:
https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/2ba4920707e95fec26e2ede8dbd7965762d55653/ansible/roles/letsencrypt/tasks/main.yml#L65

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/2ba4920707e95fec26e2ede8dbd7965762d55653/ansible/roles/letsencrypt/tasks/main.yml#L137

**Comment by rbo** [comment]
Thanks for the issue report.

`le_letsencrypt_account_email` is set  at 

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/create.yml#L25

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/certificate-renewal.yml#L13

Might be not very intuitive. 

Can you provide us your cluster.yml (without account or password information), exact errors, and command?

**Comment by weizenberg** [comment]
OK, I know what was the issue. 

I set a `letsencrypt_account_email` together with the `cloudflare_account_email`, but used different emails, so the Let'sEncrpyt task took the `letsencrypt_account_email` when tried to auth with Cloudflare, and this lead to the auth issue.

I think better to take the `cloudflare_account_email` as the first value in the following `le_letsencrypt_account_email` condition:

` le_letsencrypt_account_email: "{{ default(cloudflare_account_email) | letsencrypt_account_email }}" `

**Comment by rbo** [comment]
good point, we will fix this.

**Comment by rbo** [comment]
Fixed in devel will be merged into master with #126
