### ISSUE TITLE
Should add support to external access to api-int

### ISSUE THREAD

**Issue by weizenberg** [RedHat-EMEA-SSA-Team/hetzner-ocp4#128]
Hello,

In case of adding new **external** worker to the cluster, the api-int should be available outside the cluster. 

Should add the public ip here:
https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/6b29261ab170fe3475c4741e384a54b2ead9b7f3/ansible/roles/openshift-4-cluster/tasks/create-network.yml#L45

And add the api-int endpoint to the dns as well.

**Comment by rbo** [comment]
Hi, 

and add a public IP adress to all nodes, how do you handle that? 

Thanks
Robert

**Comment by weizenberg** [comment]
Sorry, I mean to use 0.0.0.0 in addition to 127.0.0.1

**Comment by rbo** [comment]
There some adjustments needed:

- Add public listen address for machine config server: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/create-network.yml#L45
- Add api-int to public dns https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/public_dns/tasks/create.yml#L13 https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/public_dns/tasks/create.yml#L31 https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/public_dns/tasks/create.yml#L52
- Allow 22623 to connect from public https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/prepare-host-RedHat-8.yml#L45 https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/prepare-host-RedHat-7.yml#L60 https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/b2bb6acffa9a8e9d2a69fc9bccf0f50223fa3640/ansible/roles/openshift-4-cluster/tasks/prepare-host-CentOS-8.yml#L47 

I'm not sure we want that. At the same time, I am working on an add-on function, here I could imagine that.

**Comment by weizenberg** [comment]
Yes, exactly. I used an external root server with RHEL as an additional worker instance, so it was necessary to make these changes manually.  

I agree it could be insecure in prod environments, so add-on with a warning about the security should be with ok. 

What do you think?

**Comment by rbo** [comment]
Site note:  bring-your-own RHEL 7  will be dropping at OpenShift 4.9.  

Make api-int (only 6443) public available is not a big deal, but machine config operator (22623)... But add-on is fine for me.

**Comment by rbo** [comment]
Add-on is available in master tree, with documentation. To be honest I don't know if it is possible to set up all necessary steps via post-install add-ons.

It is not planned to expose api-int to the public by default. I will close this issue. 

If you have any further questions, please let me know or open again.
