### ISSUE TITLE
CoreOS change to 4.5.6 failed

### ISSUE THREAD

**Issue by mschindl** [RedHat-EMEA-SSA-Team/hetzner-ocp4#129]
Error message:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "**Unable to find a checksum for file** 'rhcos-4.5.6-x86_64-qemu.x86_64.qcow2.gz' in 'https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.6/sha256sum.txt'"}

checksum file is available...
https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.6/sha256sum.txt

OCP running still well with 4.5.2

**Comment by rbo** [comment]
Oh you run into an ansible bug. Let me check my notes...

**Comment by rbo** [comment]
https://github.com/ansible/ansible/issues/71420

Work-a-round: remove the checksum line 44 at ansible/roles/openshift-4-cluster/tasks/download-openshift-artifacts.yml - ugly but helps.

**Comment by rbo** [comment]
Work-a-round added in ef489d1572c3607c40859fcce45254062a6acf0d (devel branch) will be merged into master with PR #126
