### ISSUE TITLE
System Requirements and Possibility on a VM?

### ISSUE THREAD

**Issue by ridvan70** [RedHat-EMEA-SSA-Team/hetzner-ocp4#132]
Hi,

what are the root server requirements and ist possible to install it on a VM?

Chers,
Ridvan

**Comment by rbo** [comment]
Hi Ridvan,

no, you need a bare metal server. Because the playbooks create a bunch of VM's. 

Cheers
Robert

**Comment by ridvan70** [comment]
Hi Robert,

What is the minimum bare metal requirements?

Thanks

**Comment by tahonen** [comment]
It depends, what are you going to do with the OCP cluster. I would say 10-12 cores, 128 Gb memory and at least 500 Gb disk. SSD disk works way better that spinning. More memory and cores you have, the better.
