### ISSUE TITLE
Accessing the cluster with auth_htpasswd values

### ISSUE THREAD

**Issue by ridvan70** [RedHat-EMEA-SSA-Team/hetzner-ocp4#133]
Hi,

I have left the default values in auth_htpasswd, for a test installation, but I can login neither to web console nor with oc client with those credentials: Invalid login or password

Are the  auth_htpasswd values encrypted or  what are default credentials?

Cheers
Ridvan

**Comment by rbo** [comment]
Hi Ridvan,

oh good questions, i don't know. 

You can use the kubeadmin credentials:
```
$ cd hetzner-ocp4
$ export KUBECONFIG=<cluster-name>/auth/kubeconfig
# Get web console URL:
$ oc get routes/console -n openshift-console
NAME      HOST/PORT                                                             PATH   SERVICES   PORT    TERMINATION          WILDCARD
console   console-openshift-console.apps......          console    https   reencrypt/Redirect   None
# get kubeadmin password:
$ cat <cluster-name>/auth/kubeadmin-password
XXXXX-mexDY-seyqD-Pjz5x
```

Open the web console URL in your browser and select "kube:admin" username: kubeadmin password is content of `<cluster-name>/auth/kubeadmin-password`

To update the htpasswd content edit the secrets htpasswd at openshift-config namespace.

To create htpasswd file lines use htpasswd cli:
```
# htpasswd -nb[mBdps] [-C cost] username password
$ htpasswd -nb admin openshift
admin:$apr1$k5WdDLwM$TzqDd.juwTiotMbctaxJt.
```

Hope that helps

**Comment by rbo** [comment]
Updated example at devel branch. Will be merged later...

**Comment by rbo** [comment]
I will close the Issue, feel free to reopen if case you have further questions on this.
