### ISSUE TITLE
CO "Marketplace Operator" in state "unknown" - OCP V 4.5.13

### ISSUE THREAD

**Issue by tux1980** [RedHat-EMEA-SSA-Team/hetzner-ocp4#134]
Hi,

I have been experiencing a failure with the Market-Place" Operator without doing anything to the cluster. It was just running fine until it wasn't:). 
Regarding the Openshift NS "openshift-marketplace", there are no problems with the CO and the Operator Hub at all and in the NS  "openshift-marketplace" all PODS are up and running without any problems. I do have neither logs or events which might indicate that there is any problems with the marketplace-operator. An yet, the cluster operator is in the state "unknown". I do not know anymore where to look elsewhere to get a grip on this Issue. 
![co_marletplace](https://user-images.githubusercontent.com/46625474/96958899-03543b80-14ff-11eb-9c42-76baa834d52d.png)

**Comment by tahonen** [comment]
I have not seen this earlier, have you tried testing killing all pods from openshift-marketplace namespace.

**Comment by tux1980** [comment]
Hi, yes, did kill the Pods from that NS several times, The all have been created successfully again after I did kill them.

**Comment by tux1980** [comment]
@tahonen In the case you can spare some minutes, glady take a look yourself, it is a demo cluster, you cannot destroy anything;)
https://console-openshift-console.apps.ocp4.kimmlingen.org/dashboards 
Local-Login:
wmarx
redhat123!

BR

**Comment by rbo** [comment]
@tux1980  I deleted your comment because of security reasons, please share credentials only private.

**Comment by rbo** [comment]
```
$ oc logs marketplace-operator-78f6f57c5b-dmnkv
time="2020-10-23T08:08:26Z" level=info msg="Go Version: go1.13.4"
time="2020-10-23T08:08:26Z" level=info msg="Go OS/Arch: linux/amd64"
time="2020-10-23T08:08:26Z" level=info msg="operator-sdk Version: v0.8.0"
time="2020-10-23T08:08:26Z" level=info msg="TLS keys set, using https for metrics"
time="2020-10-23T08:08:26Z" level=info msg="[metrics] Registering marketplace metrics"
time="2020-10-23T08:08:26Z" level=info msg="[metrics] Creating marketplace metrics RoundTripperFunc"
time="2020-10-23T08:08:26Z" level=info msg="[metrics] Serving marketplace metrics"
time="2020-10-23T08:08:26Z" level=info msg="Config API is available"
time="2020-10-23T08:08:26Z" level=info msg="Registering Components."
time="2020-10-23T08:08:26Z" level=info msg="Waiting to become leader."
```
It looks like the marketplace has problems with the leader election...

**Comment by rbo** [comment]
```
$ oc delete configmap/marketplace-operator-lock
configmap "marketplace-operator-lock" deleted
$ oc delete pod marketplace-operator-78f6f57c5b-dmnkv
pod "marketplace-operator-78f6f57c5b-dmnkv" deleted
$  oc get co/marketplace
NAME          VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
marketplace   4.5.13    False       False         False      2d19h
```

Fixed.

**Comment by rbo** [comment]
Ah wait a second AVAILABLE false

**Comment by rbo** [comment]
Normal output of marketplace-operator:
```
time="2020-10-23T08:20:49Z" level=info msg="Go Version: go1.13.4"
time="2020-10-23T08:20:49Z" level=info msg="Go OS/Arch: linux/amd64"
time="2020-10-23T08:20:49Z" level=info msg="operator-sdk Version: v0.8.0"
time="2020-10-23T08:20:49Z" level=info msg="TLS keys set, using https for metrics"
time="2020-10-23T08:20:49Z" level=info msg="[metrics] Registering marketplace metrics"
time="2020-10-23T08:20:49Z" level=info msg="[metrics] Creating marketplace metrics RoundTripperFunc"
time="2020-10-23T08:20:49Z" level=info msg="[metrics] Serving marketplace metrics"
time="2020-10-23T08:20:49Z" level=info msg="Config API is available"
time="2020-10-23T08:20:49Z" level=info msg="Registering Components."
time="2020-10-23T08:20:49Z" level=info msg="Waiting to become leader."
time="2020-10-23T08:20:49Z" level=info msg="Elected leader."
time="2020-10-23T08:20:49Z" level=info msg="Starting the Cmd."
....
```

**Comment by tahonen** [comment]
Deleted operator and then lock configmap, now updated to 4.5.15

**Comment by rbo** [comment]
Fixed.
$ oc delete deployment/marketplace-operator
$ oc delete rs -l name=marketplace-operator

**Comment by tux1980** [comment]
Hi, thanks a lot. This saved me a lot of work!

TA
Wolfgang
