### ISSUE TITLE
Manual steps necessary due to provisioning and installation on different systems

### ISSUE THREAD

**Issue by dominikhahn** [RedHat-EMEA-SSA-Team/hetzner-ocp4#144]
Is there a special reason why the installation should be done on the host itself? Manual steps are necessary on different systems (provision from localhost, install on remote). Would it be worth thinking about rewriting some snippets to run everything from a local (or CI/CD) host?

**Comment by rbo** [comment]
In the pipeline folder is an example pipeline to run the whole stuff from hetzner prov. to cluster-install in a tekton pipeline. Maybe that helps... I need I can deploy the pipeline at a RH internal cluster and demonstrate it.

**Comment by dominikhahn** [comment]
All right thanks for the clarification!
