### ISSUE TITLE
BUG in ansible-playbook ansible/setup - failed: iptables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by kirson-git** [RedHat-EMEA-SSA-Team/hetzner-ocp4#146]
There is a BUG in RHEL8 - its warning messages only and can be ignored.
However - the install fails because of it - info below.

https://access.redhat.com/solutions/4733121 

ASK [openshift-4-cluster : Active network erez] *********************************************************************************************************************************
Tuesday 01 December 2020  22:07:37 +0100 (0:00:00.304)       0:00:17.496 ******
fatal: [localhost]: FAILED! => {"changed": false, "msg": "COMMAND_FAILED: '/usr/sbin/iptables -w10 -w --table filter --insert LIBVIRT_INP --in-interface virbr1 --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: No chain/target/match by that name.\n"}

**Comment by kirson-git** [comment]
HOT FIX >
Added 
ignore_unreachable: yes in Firewalld ansible script

**Comment by milles9393** [comment]
also getting this issue, will try to hotfix.

**Comment by tux1980** [comment]
Can't install the SSA Method on RHEL 8.3 
@kirson-git You said already this is not the best workaround but where exactly I can out in this parameter to try it out myself:
ignore_unreachable: yes

TA

**Comment by Oscarlind** [comment]
@tux1980 

The task is in here: hetzner-ocp4/ansible/roles/openshift-4-cluster/tasks/create-network

FYI, it bugged out on a CentOS 8.2 machine a few times as well (as in, did not start the network). Rerunning the playbook a few times did work though.

**Comment by iboernig** [comment]
I am currently hitting this also in CentOS Stream 8.
But 
ignore_unreachable: yes 
in the failing task (active network "{{ cluster_name }} does not fix it here.

**Comment by iboernig** [comment]
I debugged this a bit:
It seems that firewalld has los all the chains coming from libvirt.
So I created a task in the beginning of this task file that restarts libvirtd.

# workaround issue #146
- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted
# workaround issue # 146

That does the trick and now it works.
Should I create a PR for this workaround?

**Comment by rbo** [comment]
It looks like there is a timing issue too, if you rerun the playbook it works too. (Tested on RHEL 8.3)

**Comment by kirson-git** [comment]
I think rebooting ( not a fan ) - solves or clean the firewalld table

**Comment by rbo** [comment]
Fixed in devel branch, will be merged into master via PR #159
