### ISSUE TITLE
console-login-helper-messages-issuegen.service -> failed

### ISSUE THREAD

**Issue by milles9393** [RedHat-EMEA-SSA-Team/hetzner-ocp4#148]
Hi,

Trying to use this playbook in order to install an OCP cluster. Facing some issues during the bootstrap process. It is currently returning ```---
[systemd]
Failed Units: 1
  console-login-helper-messages-issuegen.service```

The only thing ive changed besides from the Install Instructions is adding  "- api-int" under "with_items". 

When i run podman ```exec -ti openshift-4-loadbalancer-demo ./watch-stats.sh``` it shows connection refused on master nodes etc. 

```- name: Create DNS record at Route53
  route53:
    state: present
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
  - api
  - '*.apps'
  - api-int
  when: pd_provider == "route53"
  tags:
    - public_dns```

**Comment by rbo** [comment]
Hi,

that sound strange because api-int is provided via internal dns (libvirt dnsmasql) :

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/ansible/roles/openshift-4-cluster/templates/network.xml.j2#L11 

Do you have more details? 

Thanks
Robert

**Comment by rbo** [comment]
No response => closed. Feel free to reopen.
