### ISSUE TITLE
Installing on CentOS8  Stream: Firewalld recognized as "unknown" state.

### ISSUE THREAD

**Issue by iboernig** [RedHat-EMEA-SSA-Team/hetzner-ocp4#150]
[root@bigmachine hetzner-ocp4]# cat /etc/centos-release 
CentOS Stream release 8

[root@bigmachine hetzner-ocp4]# cat /etc/centos-release 
CentOS Stream release 8
[root@bigmachine hetzner-ocp4]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-12-14 20:46:30 CET; 3min 54s ago
     Docs: man:firewalld(1)
 Main PID: 7846 (firewalld)
    Tasks: 2 (limit: 1647948)
   Memory: 26.5M
   CGroup: /system.slice/firewalld.service
           └─7846 /usr/libexec/platform-python -s /usr/sbin/firewalld --nofork --nopid

[root@bigmachine hetzner-ocp4]# ansible-playbook -vvv ansible/setup.yml 
[...]
2020-12-14 20:51:20,113 p=8243 u=root n=ansible | Read vars_file '../cluster.yml'
2020-12-14 20:51:20,113 p=8243 u=root n=ansible | TASK [openshift-4-cluster : Enable & Start firewalld] *******************************************************
**************************************************
2020-12-14 20:51:20,113 p=8243 u=root n=ansible | Monday 14 December 2020  20:51:20 +0100 (0:00:00.832)       0:00:03.006 ******* 
2020-12-14 20:51:20,363 p=8326 u=root n=ansible | Using module file /usr/lib/python3.6/site-packages/ansible/modules/system/systemd.py
2020-12-14 20:51:20,363 p=8326 u=root n=ansible | Pipelining is enabled.
2020-12-14 20:51:20,363 p=8326 u=root n=ansible | <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
2020-12-14 20:51:20,363 p=8326 u=root n=ansible | <127.0.0.1> EXEC /bin/sh -c '/usr/libexec/platform-python && sleep 0'
2020-12-14 20:51:20,588 p=8243 u=root n=ansible | fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": false,
            "enabled": true,
            "force": null,
            "masked": null,
            "name": "firewalld",
            "no_block": false,
            "scope": null,
            "state": "started",
            "user": null
        }
    },
    "msg": "Service is in unknown state",
    "status": {}
}
2020-12-14 20:51:20,590 p=8243 u=root n=ansible | PLAY RECAP ****************************************************************************************************************************************************
2020-12-14 20:51:20,590 p=8243 u=root n=ansible | localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

What is happening here?

**Comment by iboernig** [comment]
This is even more crazy:ansible systemd seems to be broken at all:
[root@bigmachine hetzner-ocp4]# systemctl status chronyd
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-12-14 20:29:32 CET; 34min ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
 Main PID: 1226 (chronyd)
    Tasks: 1 (limit: 1647948)
   Memory: 3.3M
   CGroup: /system.slice/chronyd.service
           └─1226 /usr/sbin/chronyd

[root@bigmachine hetzner-ocp4]# ansible localhost -m systemd -a "name=chronyd state=started"
localhost | FAILED! => {
    "changed": false,
    "msg": "Service is in unknown state",
    "status": {}
}

[root@bigmachine hetzner-ocp4]# ansible --version
ansible 2.9.15
  config file = /root/hetzner-ocp4/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  3 2020, 18:11:24) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

**Comment by koep** [comment]
Related? https://github.com/ansible/ansible/issues/71528#issuecomment-729778048

**Comment by iboernig** [comment]
Good catch. So I have to wait for ansible 2.9.16? I begin to hate the pip/python-hell....

**Comment by iboernig** [comment]
Interesting.On Fedora it seems to work:
[iboernig@t470 ~]$ cat /etc/fedora-release 
Fedora release 33 (Thirty Three)
[iboernig@t470 ~]$ sudo ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
[iboernig@t470 ~]$ sudo ansible localhost -m systemd -a "name=chronyd state=started"
localhost | SUCCESS => {
    "changed": false,
    "name": "chronyd",
    "state": "started",
    "status": {
        "ActiveEnterTimestamp": "Thu 2020-12-03 13:10:00 CET",
        "ActiveEnterTimestampMonotonic": "17717685",
        "ActiveExitTimestampMonotonic": "0",
        "ActiveState": "active",
[...]

Note that Fedora and CentOS Stream 8 use the same ansible version. Only the python version is different.

**Comment by iboernig** [comment]
Oops. This seems to be a bug in systemd:
https://github.com/systemd/systemd/pull/16420

Fedora:
[iboernig@t470 ~]$ rpm -q systemd
systemd-246.7-2.fc33.x86_64
CentOS 8 Stream:
[root@bigmachine hetzner-ocp4]# rpm -q systemd
systemd-239-43.el8.x86_64

**Comment by iboernig** [comment]
Latest RHEL seems to work though:
[root@insightsclient-8 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.3 (Ootpa)

[root@insightsclient-8 ~]# ansible --version
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

[root@insightsclient-8 ~]# rpm -q systemd
systemd-239-41.el8_3.x86_64

So the error is introduced in between systemd-239-41 and  systemd-239-43...

**Comment by iboernig** [comment]
Ansible 2.9.16 landed in CentOS stream and this fixed this problem.

**Comment by iboernig** [comment]
closing this Issue then, because it was only observed in CentOS Stream 8 before ansible-2.9.16 was available.
