### ISSUE TITLE
Installing OKD cluster fails

### ISSUE THREAD

**Issue by Archehandoro** [RedHat-EMEA-SSA-Team/hetzner-ocp4#180]
Hello,

Thanks for the work put into the playbook. Trying to install the cluster using OKD always fails trying to download the opm-linux package, independently of the version used. The error is as follows:

`failed: [localhost] (item=https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-10-15-235428/opm-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz) => {"ansible_loop_var": "item", "cache_control": "no-cache", "changed": false, "connection": "close", "content": "", "content_length": "9", "content_security_policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'", "content_type": "text/plain; charset=utf-8", "date": "Sun, 04 Jul 2021 22:37:38 GMT", "elapsed": 0, "expect_ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"", "item": "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-10-15-235428/opm-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz", "msg": "Status code was 404 and not [200, 403]: HTTP Error 404: Not Found", "permissions_policy": "interest-cohort=()", "redirected": false, "referrer_policy": "no-referrer-when-downgrade", "server": "GitHub.com", "status": 404, "strict_transport_security": "max-age=31536000; includeSubdomains; preload", "url": "https://github.com/openshift/okd/releases/download/4.5.0-0.okd-2020-10-15-235428/opm-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz", "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With", "x_content_type_options": "nosniff", "x_frame_options": "deny", "x_github_request_id": "BB2E:136C2:7C2ECCD:7F8238C:60E23832", "x_xss_protection": "0"}
`

Looking at the okd repo, in releases, I can't see any file named "opm-linux-4.5.0-0.okd-2020-10-15-235428.tar.gz", is it now bundled with another one? If I remove that download from the playbook will it work or will it create a cluster with missing elements?

Thanks!

**Comment by rbo** [comment]
Hi @Archehandoro, OPM is not necessary for a successful installation.   

OPM is important to get the OperatorHub working in a disconnected/air-gapped environment.  

Let me check if we can handle this better for OKD installation.

As a work-a-round, you can remove the download from the playbook, right.

**Comment by Archehandoro** [comment]
Aaahhh you did all the work even before I could reply! Thanks so much!
