### ISSUE TITLE
add a link to virt cheatsheet

### ISSUE THREAD

**Issue by lucamaf** [RedHat-EMEA-SSA-Team/hetzner-ocp4#187]
Since not everybody is infra knowledgeable , it might be useful to add some reference command cheat-sheet to the most typical kvm commands or a link to docs, like this one : https://computingforgeeks.com/virsh-commands-cheatsheet/

**Comment by rbo** [comment]
Good point added to "Additional documentation" section.

**Comment by rbo** [comment]
Will be merged into master with PR #186
