### ISSUE TITLE
Load Balancer fails to start

### ISSUE THREAD

**Issue by Archehandoro** [RedHat-EMEA-SSA-Team/hetzner-ocp4#192]
Hello,

I'm trying to run the playbook in a home server, but I'm failing to run at because the load balancer never starts (or so the playbook says... more on this later)

Ansible fails with:

```
TASK [Check openshift-4-loadbalancer-don.service] *******************************************************************************************************************************************************************************************
Wednesday 01 September 2021  21:34:02 +0100 (0:00:00.921)       0:00:09.955 *** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Load balancer service openshift-4-loadbalancer-don.service is not running!!! Please check, run: systemctl status openshift-4-loadbalancer-don.service"}
```

systemd returns:

```
● openshift-4-loadbalancer-don.service - OpenShift 4 LoadBalancer (openshift-4-loadbalancer-don)
   Loaded: loaded (/etc/systemd/system/openshift-4-loadbalancer-don.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-09-01 21:38:37 BST; 12s ago
  Process: 53950 ExecStart=/usr/bin/podman run --name openshift-4-loadbalancer-don --net host --env-host=true quay.io/redhat-emea-ssa-team/openshift-4-loadbalancer:master (code=exited, status=1/FAILURE)
  Process: 53903 ExecStartPre=/usr/bin/podman pull quay.io/redhat-emea-ssa-team/openshift-4-loadbalancer:master (code=exited, status=0/SUCCESS)
  Process: 53857 ExecStartPre=/usr/bin/podman rm openshift-4-loadbalancer-don (code=exited, status=0/SUCCESS)
 Main PID: 53950 (code=exited, status=1/FAILURE)
```

However, through cockpit I can see the load balancer is actually running:

![image](https://user-images.githubusercontent.com/24658788/131742201-5696953c-f710-4bd9-9b5e-5391e36030cf.png)

But there isn't anything showing the logs. If I force stop the container, then the systemd unit keeps cycling it.

Any ideas what could it be?

Thanks!

**Comment by Archehandoro** [comment]
I found the issue. My home server has only one NIC, and I'm not using it as a router, therefore the public_ip variable stated in the Ansible Playbook was not its real IP, but the external IP from my ISP provider. Changing the value to the private IP of the server works, the LB stays running, and the cluster creates successfully. The only change needed in the router is port forwarding to the server/LB IP.

However, this affects the public_ip sent to the DNS providers. If people are interested, I will try to send a PR with changes to make different the IP of the LB and the public_ip var for DNS.

**Comment by rbo** [comment]
Of course, if would suggest: 
 * Run the installation with your private ip address  + `dns_provider: none`
 * and write an [add-on](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/docs/add-ons.md) to add the public DNS entries + letsencrypt stuff if needed.
