### ISSUE TITLE
metallb

### ISSUE THREAD

**Issue by lucamaf** [RedHat-EMEA-SSA-Team/hetzner-ocp4#213]
would it make sense to use metallb instead of haproxy, so that we can easily expose multiple services with a shared public IP address using simple configmap and deployments?

**Comment by rbo** [comment]
Maybe I don't get it, but if metal lb is installed in OpenShift it has only access to the private kvm network and not to the hetzner/public_ip network:

![image](https://raw.githubusercontent.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/6317baeb37a5089e3e672b395afaa36bc59208a1/images/architecture.png)

HAProxy is dispatching/forwarding the traffic from public IP to the private kvm network.

**Comment by lucamaf** [comment]
that's correct, I guess I was trying to find an easier way to modify the exposed port so that direct access to TCP services inside OpenShift would be possible, but of course MetalLB has to run inside OpenShift.
Any other workaround for HAProxy on this point?

**Comment by rbo** [comment]
You can adjust the haproxy by hand:

```
$ systemctl cat openshift-4-loadbalancer-$CLUSTER_NAME$
# /etc/systemd/system/openshift-4-loadbalancer-$CLUSTER_NAME$.service
[Unit]
Description=OpenShift 4 LoadBalancer (openshift-4-loadbalancer-demo)
After=network.target

[Service]
Type=simple
TimeoutStartSec=5m

EnvironmentFile=/etc/sysconfig/openshift-4-loadbalancer-$CLUSTER_NAME$.env

ExecStartPre=-/usr/bin/podman rm "openshift-4-loadbalancer-$CLUSTER_NAME$"
ExecStartPre=/usr/bin/podman pull quay.io/redhat-emea-ssa-team/openshift-4-loadbalancer:master
ExecStart=/usr/bin/podman run --name openshift-4-loadbalancer-$CLUSTER_NAME$ --net host \
  --env-host=true \
  quay.io/redhat-emea-ssa-team/openshift-4-loadbalancer:master

ExecReload=-/usr/bin/podman stop "openshift-4-loadbalancer-$CLUSTER_NAME$"
ExecReload=-/usr/bin/podman rm "openshift-4-loadbalancer-$CLUSTER_NAME$"
ExecStop=-/usr/bin/podman stop "openshift-4-loadbalancer-$CLUSTER_NAME$"
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

Checkout the line:
```
EnvironmentFile=/etc/sysconfig/openshift-4-loadbalancer-$CLUSTER_NAME$.env
```

This file contains the entire haproxy configuration, you can change the configuration and restart the haproxy. What do you think?

**Comment by lucamaf** [comment]
but I would need to rebuild the image right? isn't haproxy running on podman?
does my use case make any sense at all? exposing easily TCP services or am I missing some feature that will allow you to do that in a more k8s way?

**Comment by rbo** [comment]
Nope, the image is fetching the haproxy config from an environment variable.
