### ISSUE TITLE
Issue: Create DNS record at Route53

### ISSUE THREAD

**Issue by tux1980** [RedHat-EMEA-SSA-Team/hetzner-ocp4#214]
Hi,
getting this error message with my Installation on my hetzner server being at the point:
TASK [public_dns: Create DNS record at Route53]

Did anyone of you encounter this message either?

OS: RHEL 8.5, ansible 2.9.27

-----------------------------
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: boto.exception.BotoServerError: BotoServerError: 400 Bad Request
failed: [localhost] (item=api) => {"ansible_loop_var": "item", "changed": false, "item": "api", "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_route53_payload_9cpm1e8t/ansible_route53_payload.zip/ansible/modules/cloud/amazon/route53.py\", line 701, in <module>\n  File \"/tmp/ansible_route53_payload_9cpm1e8t/ansible_route53_payload.zip/ansible/modules/cloud/amazon/route53.py\", line 600, in main\n  File \"/tmp/ansible_route53_payload_9cpm1e8t/ansible_route53_payload.zip/ansible/modules/cloud/amazon/route53.py\", line 392, in get_zone_id_by_name\n  File \"/tmp/ansible_route53_payload_9cpm1e8t/ansible_route53_payload.zip/ansible/modules/cloud/amazon/route53.py\", line 456, in invoke_with_throttling_retries\n  File \"/tmp/ansible_route53_payload_9cpm1e8t/ansible_route53_payload.zip/ansible/modules/cloud/amazon/route53.py\", line 452, in invoke_with_throttling_retries\n  File \"/usr/local/lib/python3.6/site-packages/boto/route53/connection.py\", line 559, in get_zones\n    zones = self.get_all_hosted_zones()\n  File \"/usr/local/lib/python3.6/site-packages/boto/route53/connection.py\", line 120, in get_all_hosted_zones\n    params=params)\n  File \"/usr/local/lib/python3.6/site-packages/boto/route53/connection.py\", line 103, in make_request\n    retry_handler=self._retry_handler)\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 1071, in make_request\n    retry_handler=retry_handler)\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 1028, in _mexe\n    raise BotoServerError(response.status, response.reason, body)\nboto.exception.BotoServerError: BotoServerError: 400 Bad Request\n\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by rbo** [comment]
Looks like it's related to #206 & #205, please try the devel tree with new ansible execution env. & ansible-navigator solution:

----
Problem is fixed with the change to ansible execution environment (#207) in Devel will be merge into Master with #212

Please checkout the the devel tree.

In short:
1) Install ansible navigator 
     - [RHEL](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/tree/devel#in-case-of-red-hat-enterprise-linux-8)
     - [Rocky/Centos](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/tree/devel#in-case-of-rocky-linux-8-or-centos-8) 
2) Checkout devel branch
3) Run playbooks: `ansible-navigator run -m stdout ./ansible/setup.yml`
-----

**Comment by tux1980** [comment]
I did as stated above. Also with the command (devel branch if course) ansible-navigator run -m stdout ./ansible/setup.yml - the error keeps the same than before. Something with boto3 / wrong ansible python interpreter. 

----------
TASK [public_dns : Create DNS record at Route53] *******************************
failed: [host] (item=api) => {"ansible_loop_var": "item", "changed": false, "item": "api", "msg": "Failed to import the required Python library (botocore or boto3) on openshift.kimmlingen.local's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
failed: [host] (item=*.apps) => {"ansible_loop_var": "item", "changed": false, "item": "*.apps", "msg": "Failed to import the required Python library (botocore or boto3) on openshift.kimmlingen.local's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

-----------------------------
Bit more output:
TASK [public_dns : Create DNS record at Route53] *******************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListHostedZones operation: Signature expired: 20220421T145651Z is now earlier than 20220421T145718Z (20220421T150218Z - 5 min.)
failed: [host] (item=api) => {"ansible_loop_var": "item", "changed": false, "item": "api", "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553010.6692488-314-79581318482768/AnsiballZ_route53.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553010.6692488-314-79581318482768/AnsiballZ_route53.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553010.6692488-314-79581318482768/AnsiballZ_route53.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 708, in <module>\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 587, in main\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 406, in get_zone_id_by_name\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 125, in _retry_wrapper\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 68, in _retry_func\r\n  File \"/tmp/ansible_route53_payload_n2gvyzwc/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 384, in _list_hosted_zones\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 449, in build_full_result\r\n    for response in self:\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 253, in __iter__\r\n    response = self._make_request(current_kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 332, in _make_request\r\n    return self._method(**current_kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 415, in _api_call\r\n    return self._make_api_call(operation_name, kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 745, in _make_api_call\r\n    raise error_class(parsed_response, operation_name)\r\nbotocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListHostedZones operation: Signature expired: 20220421T145651Z is now earlier than 20220421T145718Z (20220421T150218Z - 5 min.)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListHostedZones operation: Signature expired: 20220421T145651Z is now earlier than 20220421T145719Z (20220421T150219Z - 5 min.)
failed: [host] (item=*.apps) => {"ansible_loop_var": "item", "changed": false, "item": "*.apps", "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553011.5973957-314-180313842050194/AnsiballZ_route53.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553011.5973957-314-180313842050194/AnsiballZ_route53.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1650553011.5973957-314-180313842050194/AnsiballZ_route53.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 708, in <module>\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 587, in main\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 406, in get_zone_id_by_name\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 125, in _retry_wrapper\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 68, in _retry_func\r\n  File \"/tmp/ansible_route53_payload_k9e1sjdv/ansible_route53_payload.zip/ansible_collections/community/aws/plugins/modules/route53.py\", line 384, in _list_hosted_zones\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 449, in build_full_result\r\n    for response in self:\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 253, in __iter__\r\n    response = self._make_request(current_kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/paginate.py\", line 332, in _make_request\r\n    return self._method(**current_kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 415, in _api_call\r\n    return self._make_api_call(operation_name, kwargs)\r\n  File \"/usr/local/lib/python3.6/site-packages/botocore/client.py\", line 745, in _make_api_call\r\n    raise error_class(parsed_response, operation_name)\r\nbotocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListHostedZones operation: Signature expired: 20220421T145651Z is now earlier than 20220421T145719Z (20220421T150219Z - 5 min.)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by rbo** [comment]
it looks like boto python lib is missing. I updated the image `quay.io/redhat-emea-ssa-team/hetzner-ocp4-ansible-ee:devel`. Please try to pull `quay.io/redhat-emea-ssa-team/hetzner-ocp4-ansible-ee:devel` again and re-run the playbook.

**Comment by tux1980** [comment]
Hi, tried that out again - no success unfortunately.

**Comment by rbo** [comment]
@tux1980 please update your local devel branch, I made some changes at the ansible/roles/playbooks. And test it again please. Thanks

**Comment by tux1980** [comment]
Hi, 

this is unfortunately still not working with the very same error:
ansible-navigator run -m stdout ./ansible/setup.yml --eei quay.io/redhat-emea-ssa-team/hetzner-ocp4-ansible-ee:devel

The changes I noticed in the env Files for the eei origin from  26.04., so it should be the most updated version.

Under normal Circumstances I would have installed the Server from scratch (like I did it with my CentOS, where everything is working fine). 
But on this server I also presenting stuff like Satellite and other useful things....
Wolfgang

**Comment by tux1980** [comment]
It was a local time drift of 2 minutes, therefore the signature of my AWS Key was declared invalid for reasons of Security @AWS. Sorry :(
