### ISSUE TITLE
letsencrypt requires running a renewal-certificate playbook

### ISSUE THREAD

**Issue by dmarrazzo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#215]
Hi all,
not sure if it's a glitch of my personal installation, but after the setup playbook, the certificate were not signed.
I had to run manually renewal-certificate playbook which solved my problem.

BTW, I believe that is worth mentioning to existence of `renewal-certificate` playbook in the doc.

Thank you

**Comment by rbo** [comment]
Yes, you have to run renewal-certificate playbook manually on your one. There is no automatic renew process.  To be honest, my cluster don't live that long... 

I added some documentation with commit 8af050eeaac8c3a6b3dcc3b146927767aeb99c44
