### ISSUE TITLE
OCP upgrades failing due to IPv6 being used and not being part of the certs

### ISSUE THREAD

**Issue by tomazb** [RedHat-EMEA-SSA-Team/hetzner-ocp4#216]
Hello!

My OCP 4.10 upgrades are failing due to IPv6 usage and those IPv6 addresses not being part of certs:

EtcdCertSignerControllerDegraded: [x509: certificate is valid for 192.168.50.10, not 2a01:4f9:4b:49d4:32::1000, x509: certificate is valid for ::1, 127.0.0.1, 192.168.50.10, ::1, not 2a01:4f9:4b:49d4:32::1000, x509: certificate is valid for 192.168.50.11, not 2a01:4f9:4b:49d4:32::1001, x509: certificate is valid for ::1, 127.0.0.1, 192.168.50.11, ::1, not 2a01:4f9:4b:49d4:32::1001, x509: certificate is valid for 192.168.50.12, not 2a01:4f9:4b:49d4:32::1002, x509: certificate is valid for ::1, 127.0.0.1, 192.168.50.12, ::1, not 2a01:4f9:4b:49d4:32::1002]

**Comment by rbo** [comment]
Oh very interesting, official IPv6 is only supported on bare metal ipi. As far as I know.

Do you have more details? Where do you get the error? Upgrade from version to version?

**Comment by tomazb** [comment]
This is from my cluster.yaml:
# DualStack:
ip_families:
  - IPv4
  - IPv6

and I have IPv6 on virbr1 configured.

So technically I need to disable IPV6 due to being a UPI setup on libvirt?

**Comment by tomazb** [comment]
Yes, by going to higher 4.10 versions. Consistently.

**Comment by rbo** [comment]
Why did you configure IPv6 on virbr1? This is all done automatic via the playbooks.

**Comment by rbo** [comment]
Feel free to reopen if you still have problems.
