### ISSUE TITLE
No module named 'kubernetes' when running "Create infra-registry pv"

### ISSUE THREAD

**Issue by dmarrazzo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#224]
the playbook fails with the following message:

```
TASK [openshift-4-cluster : Create infra-registry pv] **************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'kubernetes'
fatal: [host -> localhost]: FAILED! => {"changed": false, "error": "No module named 'kubernetes'", "msg": "Failed to import the required Python library (kubernetes) on dmshift.eu's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by rbo** [comment]
Do you tried the new `ansible-navigator` method? https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4#in-case-of-red-hat-enterprise-linux-8

**Comment by tux1980** [comment]
I have the same issue with RHEL 8.6 executing:
ansible-navigator run -m stdout  ./ansible/02-create-cluster.yml

-----------
TASK [openshift-4-cluster : Include post installation tasks] *******************
fatal: [host]: FAILED! => {"reason": "couldn't resolve module/action 'kubernetes.core.k8s'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/root/hetzner-ocp4/ansible/roles/openshift-4-cluster/tasks/post-install-storage-nfs.yml': line 65, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create infra-registry pv\n  ^ here\n"}

Any Ideas?

**Comment by tux1980** [comment]
Arghhh....
As the message indicated - maybe the module is missing? And yes, it was. Just execute:
# ansible-galaxy collection install community.kubernetes - the kubernetes.core.k8s module is included in  there.

**Comment by rbo** [comment]
mh strange, please show me your `ansible-navigator.yaml ` file. 

Because `community.kubernetes` is part of the execution environment

**Comment by dmarrazzo** [comment]
I was able to work around it using plain ansible.
I'm running CentOS Stream release 8

**Comment by rbo** [comment]
Then I would close the issue, open it again if there is still a problem.
