### ISSUE TITLE
TASK [openshift-4-cluster : Define network "CLUSTERNAME"

### ISSUE THREAD

**Issue by tux1980** [RedHat-EMEA-SSA-Team/hetzner-ocp4#228]
Hi,

with RHEL 8.6 I always get the message:
fatal: [host]: FAILED! => {"changed": false, "msg": "The `lxml` module is not importable. Check the requirements."}
The Modul is installed.

Command to reproduce:
ansible-navigator run -m stdout --eei ee-29-rhel8 ./ansible/02-create-cluster.yml

Thanks!

**Comment by tux1980** [comment]
Is running now - sorry. Wrong Independence. I mixed up P2 with P3 Modules....

**Comment by tux1980** [comment]
Closed

**Comment by tomazb** [comment]
On RHEL 8.7 I had to install python3-lxml to resolve this issue. This is missing from ansible/roles/openshift-4-cluster/tasks/prepare-host-RedHat-8.yml
