### ISSUE TITLE
Add simpler option for setting up Linux on Hetzner root server

### ISSUE THREAD

**Issue by fc7** [RedHat-EMEA-SSA-Team/hetzner-ocp4#243]
The document `docs/hetzner.md` mentions two options how to set up a Hetzner root server. 

IMHO it should add a third one, which is much simpler, especially for newcomers: Under https://robot.hetzner.com/server there is a tab "Linux" where one can select either "CentOS Stream 8 base" or "Rocky Linux 8.5 base" and activate the linux installation, and finally send the "Hardware Reset" to the server and wait. The installation is fully automatic. My experience with CentOS Stream 8 was flawless. The other options should be preferred for advanced users only.

**Comment by rbo** [comment]
Good point, documentation PR is welcome. Or write the documentation down in the Issue and I can move it into the hetzner-ocp4 repo. 

Thanks

**Comment by rbo** [comment]
Fixed with last PR
