### ISSUE TITLE
Wildcard letsencrypt certificate has been expired 

### ISSUE THREAD

**Issue by tux1980** [RedHat-EMEA-SSA-Team/hetzner-ocp4#245]
Hi,

unfortunately I cannot longer authenticate myself within the Web UI since my Let'sEncrypt Cert is not valid anymore.
Execution renewal-certificate.yml is "almost" running fine but at the end, it runs into one error.

Execution Command:
```
ansible-navigator run -m stdout  ansible/renewal-certificate.yml
```
![gnome-shell-screenshot-4o56xs](https://user-images.githubusercontent.com/46625474/210327451-41181d37-752d-4642-88a3-f2575e388f8b.png)

Anyone an Idea how to solve that? 
(the kubeconfig file is there as opposed to the error message in my running playbook)
Thanks!
Wolfgang

**Comment by tux1980** [comment]
Good morning,
the issue still is in place, couldn't solve it myself yet. Any hints or ideas?
Thanks
Wolfgang

**Comment by rbo** [comment]
mh, let me check at my env.

**Comment by rbo** [comment]
Works at my env... :-( 

Which version of hetzner-ocp4 do have in use?

Please execute: ` git show --oneline -s` 
Thanks

**Comment by tux1980** [comment]
Hi, sorry for the late response, was on vacation. 
I'm using the actual version, just donwloaded it again and also executed the command above:
git show --oneline -s

I did everything including updating my RHEL from 8.6 >> 8.7. But the error stays.  

TASK [openshift-4-cluster : Fetch kubeconfig into runner] **********************
fatal: [host]: FAILED! => {"changed": false, "msg": "the remote file does not exist, not transferring, ignored"}

any other hints or ideas?

Thanks!

**Comment by rbo** [comment]
@tux1980 puh I don't know. Feel free to add my key (https://github.com/rbo.keys) I can take a look.

**Comment by tux1980** [comment]
@rbo 
Thanks. I added the key in my authorized_keys
root@openshift.kimmlingen.org

**Comment by rbo** [comment]
@tux1980  Fixed and certificates renewed. 
```
[root@openshift hetzner-ocp4]# git diff ansible/roles/openshift-4-cluster/defaults/main.yml
diff --git a/ansible/roles/openshift-4-cluster/defaults/main.yml b/ansible/roles/openshift-4-cluster/defaults/main.yml
index f26ca2a..5b13f7f 100644
--- a/ansible/roles/openshift-4-cluster/defaults/main.yml
+++ b/ansible/roles/openshift-4-cluster/defaults/main.yml
@@ -1,6 +1,6 @@
 ---
 artifacts_dir: "{{ playbook_dir }}/.."
-openshift_install_dir: "{{ artifacts_dir }}./{{ cluster_name }}"
+openshift_install_dir: "{{ artifacts_dir }}/{{ cluster_name }}"
 ssh_public_key_location: ~/.ssh/id_rsa
 
 vn_subnet: "192.168.50.0"
[root@openshift hetzner-ocp4]# ansible-navigator run -vvv ansible/renewal-certificate.yml 
....
PLAY RECAP *********************************************************************
host                       : ok=27   changed=6    unreachable=0    failed=0    skipped=28   rescued=0    ignored=0  
```

Will fix in master & devel later.

**Comment by rbo** [comment]
Fixed in master & devel

**Comment by tux1980** [comment]
Cool, is working, thank you - put it down in my Hetzner Docu too:)
