### ISSUE TITLE
Ensure support for x86-64-v2 when creating VMs for each node

### ISSUE THREAD

**Issue by fc7** [RedHat-EMEA-SSA-Team/hetzner-ocp4#253]
This is a small but I believe meaningful enhancement request.

I am using RHEL 9 as host. With several container images, I have encountered the following issue at runtime:
```
Fatal glibc error: CPU does not support x86-64-v2
```
Based on [this](https://unix.stackexchange.com/questions/631217/how-do-i-check-if-my-cpu-supports-x86-64-v2) I checked that my CPU (Xeon E5-1650 v3) does actually satisfy the criteria for x86-64-v2:
```
# /lib64/ld-linux-x86-64.so.2 --help
<snip>
Subdirectories of glibc-hwcaps directories, in priority order:
  x86-64-v4
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)
```
The problem can actually be fixed by modifying the CPU settings of each VM to use the `host-model`. See e.g. [here](https://www.systutorials.com/docs/linux/man/1-virt-xml/). With my compact setup (3 master/worker nodes), I used the following command:
```
for n in $(seq 0 2); do
    sudo virt-xml ocp4-master-${n} --edit --cpu host-model
done
```
After restarting each VM, the issue no longer appears.

I believe it would make sense to set this automatically with the playbook already at cluster creation, when setting up the VMs of each node.

**Comment by tomazb** [comment]
Yes, this is also needed for ACS as qemu64 is not the right CPU for the job :-)

**Comment by rbo** [comment]
You can overwrite the cpu in your cluster.yml via:

```
compute_special_cpu: "<cpu mode='host-passthrough'></cpu>"
master_special_cpu: "<cpu mode='host-passthrough'></cpu>"
```

I will double check if it make sense to change the defaults because of newer os/qemu version

**Comment by fc7** [comment]
I believe `host-passthrough` has the same meaning as `host-model`. IMHO it would make sense to make this the default. Otherwise many containers may end up in a crashloop because of the glibc incompatibility.

**Comment by sluetze** [comment]
+1 for making it default and also the options should be documented outside of the [container native virtualization usecase](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/3126f2c80cb1b1491d4251ffd39f4121881fd437/docs/cnv.md), since they are needed for usecases outside of nested virtualization.

**Comment by rbo** [comment]
For testing purpose, I added `<cpu mode='host-passthrough'></cpu>`  as default.

**Comment by rbo** [comment]
Branch libvirt-xml-improvements merged into devel.

**Comment by rbo** [comment]
Released in 2023-06-22
