### ISSUE TITLE
web-terminal add-on / channelname changed

### ISSUE THREAD

**Issue by jaxx0r** [RedHat-EMEA-SSA-Team/hetzner-ocp4#295]
https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/0b1245f1cb1ec29e79695f3b2eed6ed076a0a5e6/ansible/add-on-roles/web-terminal/tasks/post-install.yml#L19

in 4.13 this should be "fast" instead of "alpha" for the channel-name to install the web-terminal operator

**Comment by rbo** [comment]
Fixed in devel. Will merged into master later.

**Comment by rbo** [comment]
Fixed in devel branch, I will merge into master with #304

Thank you for the issue.
