### ISSUE TITLE
Setup proper SELinux context for extra ports

### ISSUE THREAD

**Issue by tahonen** [RedHat-EMEA-SSA-Team/hetzner-ocp4#3]
ports are 6443 and 22623

**Comment by rbo** [comment]
Fresh installation:
```
root@harlekin:~ $ getenforce
Disabled
```

Is that default for hetzner centos 7.6 boxes?

**Comment by tahonen** [comment]
Seems to be

**Comment by rbo** [comment]
Tested with RHEL 8 (Dev branch: https://github.com/rbo/hetzner-ocp4/tree/dev ) works perfectly.

Without any SELinux adjustments, feels strange. Works out of the box...

**Comment by rbo** [comment]
Tested with RHEL 7 too. Works perfectly. RHEL 7 & 8 support will be merged with PR #75

feel free to reopen.
