### ISSUE TITLE
What/Where is pullSecret

### ISSUE THREAD

**Issue by jwalzer** [RedHat-EMEA-SSA-Team/hetzner-ocp4#309]
I try to find out that `pullSecret` in cluster.yaml is about.

I'm not seeing any documentation on what/how this should look like and how to aquire it.

Can you please add some paragraphs in the documentation

**Comment by rbo** [comment]
Do you mean:
```

image_pull_secret: |-
  asdfghfdsa

```
?

**Comment by rbo** [comment]
Checkout cluster-example.yml in repo for more examples.

**Comment by rbo** [comment]
You can copy / Download pull secret at: https://console.redhat.com/openshift/install/metal/user-provisioned

And add the content to your cluster.yaml, here you can find an example: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/blob/master/cluster-example.yml#L72

**Comment by rbo** [comment]
Eveything is here documented: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/tree/1bca5b08fd19d3174e3e0dc1a347f0a52f3a8b25?tab=readme-ov-file#define-variables-for-your-cluster
