### ISSUE TITLE
Adding OpenShift Container Storage 4 (rook & ceph)

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#31]
We have to add OpenShit Container Storage 4 (rook & ceph) because, we need storage for the Image Registry and for applications too.

Working branch: [ocs_issue#31](https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/tree/ocs_issue%2331) 
### Current status
You can install ocs upstream on OCP4 - quick'n'dirty
```
git clone git@github.com:RedHat-EMEA-SSA-Team/hetzner-ocp4.git
cd hetzner-ocp4
git branch ocs_issue#31 origin/ocs_issue#31
git checkout ocs_issue#31
# Create cluster.yml
vi cluster.yml
./ansible/02-create-cluster.yml
export KUBECONFIG=....
./deploy-ocs.sh
``` 

### ToDo

- [ ] Metrics do not work, create service monitor and metrics do not show up in cluster Prometheus.

**Comment by tahonen** [comment]
Flag to cluster.yml 

```install_ocs: false|true ```

defaults to true

**Comment by rbo** [comment]
## Installing rook & ceph upstream on OpenShift
```
oc create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/common.yaml
oc create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/operator-openshift.yaml
oc create -f https://raw.githubusercontent.com/rook/rook/master/cluster/examples/kubernetes/ceph/cluster.yaml
```
[Source](https://github.com/rook/rook/blob/master/Documentation/openshift.md)

**Comment by rbo** [comment]
Upstream is not useful, wait for the first product beta and/or GA product.

**Comment by tahonen** [comment]
We need to revisit this

**Comment by rbo** [comment]
On monday? :-)

**Comment by rbo** [comment]
branch updated

**Comment by rbo** [comment]
OCS4 is very CPU, RAM and Storage intensive. Does it makes sense to create an automatism for it?

**Comment by rbo** [comment]
Rebase branch ocs_issue#31 to devel

**Comment by rbo** [comment]
Closed, this should be an add-on. OCS is to heavy to be part of the default installation.
