### ISSUE TITLE
After updating RHEL from 8.10 > 9.4 - openshift-4-loadbalancer-ocp4.service

### ISSUE THREAD

**Issue by tux1980** [RedHat-EMEA-SSA-Team/hetzner-ocp4#316]
![Uploading Screenshot from 2024-06-18 08-45-25.png…]()
Hi,

I may have an issue with openshift-4-loadbalancer-ocp4.service after updating my hetzner from RHEL 8.10 >> 9.4. 
My 3 ocp KVM Servers are all up and running and after checking out the local coreos log(s) there most likely not in trouble. 

`Jun 18 08:38:17 openshift.kimmlingen.local openshift-4-loadbalancer-ocp4[5728]: [WARNING] 169/063817 (1) : Server ingress-http/master-0 is DOWN, reason: Layer4 conne>
Jun 18 08:38:17 openshift.kimmlingen.local podman[5689]: [WARNING] 169/063817 (1) : Server ingress-http/master-0 is DOWN, reason: Layer4 connection problem, info: "C>
Jun 18 08:38:17 openshift.kimmlingen.local podman[5689]: [ALERT] 169/063817 (1) : proxy 'ingress-http' has no server available!
Jun 18 08:38:17 openshift.kimmlingen.local openshift-4-loadbalancer-ocp4[5728]: [ALERT] 169/063817 (1) : proxy 'ingress-http' has no server available!
Jun 18 08:38:19 openshift.kimmlingen.local openshift-4-loadbalancer-ocp4[5728]: [WARNING] 169/063819 (1) : Server machine-config-server/master-0 is DOWN, reason: Lay>
Jun 18 08:38:19 openshift.kimmlingen.local podman[5689]: [WARNING] 169/063819 (1) : Server machine-config-server/master-0 is DOWN, reason: Layer4 connection problem,>
Jun 18 08:38:20 openshift.kimmlingen.local openshift-4-loadbalancer-ocp4[5728]: [WARNING] 169/063820 (1) : Server machine-config-server/master-2 is DOWN, reason: Lay>
Jun 18 08:38:20 openshift.kimmlingen.local openshift-4-loadbalancer-ocp4[5728]: [ALERT] 169/063820 (1) : proxy 'machine-config-server' has no server available!
Jun 18 08:38:20 openshift.kimmlingen.local podman[5689]: [WARNING] 169/063820 (1) : Server machine-config-server/master-2 is DOWN, reason: Layer4 connection problem,>
Jun 18 08:38:20 openshift.kimmlingen.local podman[5689]: [ALERT] 169/063820 (1) : proxy 'machine-config-server' has no server available!
`

Any Idea what that might cause and how I might solve that? 
Thanks

**Comment by tux1980** [comment]
Ok, obviously with a LEAPP Upgrade from 8 to RHEL 9 the "AllowZoneDrifting" Parameter got set to NO. After setting it to "yes" again the LB is working again and I can access the cluster voa UI and OC again.

Command:
sed -i "s/^AllowZoneDrifting=.*/AllowZoneDrifting=yes/" /etc/firewalld/firewalld.conf 
Restart FW afterwards.

**Comment by rbo** [comment]
Sounds like we can close the issue?!

**Comment by tux1980** [comment]
Yes of course sry, forgot....
