### ISSUE TITLE
bootstrap vm failes to download ocp-release-nightly image from quay

### ISSUE THREAD

**Issue by andyneeb** [RedHat-EMEA-SSA-Team/hetzner-ocp4#35]
Install fails at TASK [openshift-4-cluster : Waiting bootstrap to complete]

journalctl on bootstrap node has the following error:

Sep 17 09:25:21 bootstrap release-image-download.sh[1016]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release-nightly@sha256:d48a15ea564293934eb188e6eb8737e56903453d50bc70830cdac2641fb63acc": unable to pull quay.io/openshift-release-dev/ocp-release-nightly@sha256:d48a15ea564293934eb188e6eb8737e56903453d50bc70830cdac2641fb63acc: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release-nightly@sha256:d48a15ea564293934eb188e6eb8737e56903453d50bc70830cdac2641fb63acc: pinging docker registry returned: Get https://quay.io/v2/: dial tcp 23.23.73.73:443: i/o timeout

Curling the quay api fails as well on bootstrap vm:

[root@bootstrap ~]# curl -v https://quay.io/v2/
*   Trying 54.225.213.19...
* TCP_NODELAY set
* connect to 54.225.213.19 port 443 failed: Connection timed out
*   Trying 54.243.184.178...
* TCP_NODELAY set
* After 85578ms connect time, move on!
* connect to 54.243.184.178 port 443 failed: Connection timed out
*   Trying 23.23.73.73...
* TCP_NODELAY set
* After 42789ms connect time, move on!
* connect to 23.23.73.73 port 443 failed: Connection timed out
*   Trying 23.23.187.164...
* TCP_NODELAY set
* After 21394ms connect time, move on!
* connect to 23.23.187.164 port 443 failed: Connection timed out
*   Trying 54.243.157.21...
* TCP_NODELAY set
* After 10696ms connect time, move on!
* connect to 54.243.157.21 port 443 failed: Connection timed out
*   Trying 54.225.149.151...
* TCP_NODELAY set
* After 5347ms connect time, move on!
* connect to 54.225.149.151 port 443 failed: Connection timed out
* Failed to connect to quay.io port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to quay.io port 443: Connection timed out

Curling the quay API works fine from Hetzner root server or local laptop.

**Comment by andyneeb** [comment]
As requested:

[root@hetzner ~]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 ocp                  active     yes           yes

[root@hetzner ~]# virsh net-dumpxml ocp
<network connections='7'>
  <name>ocp</name>
  <uuid>5c2c34fa-a670-402c-8e6d-5ed4605b65da</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:dc:e5:f2'/>
  <domain name='compute.local'/>
  <dns>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-0.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-1.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-2.ocp.andyneeb.com' port='2380' weight='10'/>
    <host ip='192.168.50.2'>
      <hostname>bootstrap.compute.local</hostname>
    </host>
    <host ip='192.168.50.1'>
      <hostname>api-int.ocp.andyneeb.com</hostname>
      <hostname>api.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.10'>
      <hostname>master-0.compute.local</hostname>
      <hostname>etcd-0.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.11'>
      <hostname>master-1.compute.local</hostname>
      <hostname>etcd-1.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.12'>
      <hostname>master-2.compute.local</hostname>
      <hostname>etcd-2.ocp.andyneeb.com</hostname>
    </host>
  </dns>
  <ip address='192.168.50.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.50.10' end='192.168.50.250'/>
      <host mac='52:54:00:a8:32:02' name='bootstrap.compute.local' ip='192.168.50.2'/>
      <host mac='52:54:00:a8:32:0a' name='master-0.compute.local' ip='192.168.50.10'/>
      <host mac='52:54:00:a8:32:0b' name='master-1.compute.local' ip='192.168.50.11'/>
      <host mac='52:54:00:a8:32:0c' name='master-2.compute.local' ip='192.168.50.12'/>
      <host mac='52:54:00:a8:32:0d' name='compute-0.compute.local' ip='192.168.50.13'/>
      <host mac='52:54:00:a8:32:0e' name='compute-1.compute.local' ip='192.168.50.14'/>
      <host mac='52:54:00:a8:32:0f' name='compute-2.compute.local' ip='192.168.50.15'/>
    </dhcp>
  </ip>
</network>

**Comment by andyneeb** [comment]
As requested

ˋˋˋ
[root@hetzner ~]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 ocp                  active     yes           yes

[root@hetzner ~]# virsh net-dumpxml ocp
<network connections='7'>
  <name>ocp</name>
  <uuid>5c2c34fa-a670-402c-8e6d-5ed4605b65da</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:dc:e5:f2'/>
  <domain name='compute.local'/>
  <dns>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-0.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-1.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-2.ocp.andyneeb.com' port='2380' weight='10'/>
    <host ip='192.168.50.2'>
      <hostname>bootstrap.compute.local</hostname>
    </host>
    <host ip='192.168.50.1'>
      <hostname>api-int.ocp.andyneeb.com</hostname>
      <hostname>api.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.10'>
      <hostname>master-0.compute.local</hostname>
      <hostname>etcd-0.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.11'>
      <hostname>master-1.compute.local</hostname>
      <hostname>etcd-1.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.12'>
      <hostname>master-2.compute.local</hostname>
      <hostname>etcd-2.ocp.andyneeb.com</hostname>
    </host>
  </dns>
  <ip address='192.168.50.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.50.10' end='192.168.50.250'/>
      <host mac='52:54:00:a8:32:02' name='bootstrap.compute.local' ip='192.168.50.2'/>
      <host mac='52:54:00:a8:32:0a' name='master-0.compute.local' ip='192.168.50.10'/>
      <host mac='52:54:00:a8:32:0b' name='master-1.compute.local' ip='192.168.50.11'/>
      <host mac='52:54:00:a8:32:0c' name='master-2.compute.local' ip='192.168.50.12'/>
      <host mac='52:54:00:a8:32:0d' name='compute-0.compute.local' ip='192.168.50.13'/>
      <host mac='52:54:00:a8:32:0e' name='compute-1.compute.local' ip='192.168.50.14'/>
      <host mac='52:54:00:a8:32:0f' name='compute-2.compute.local' ip='192.168.50.15'/>
    </dhcp>
  </ip>
</network>

**Comment by andyneeb** [comment]
As requested 

```
[root@hetzner ~]# virsh net-dumpxml ocp
<network connections='7'>
  <name>ocp</name>
  <uuid>5c2c34fa-a670-402c-8e6d-5ed4605b65da</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac addre
```ss='52:54:00:dc:e5:f2'/>
  <domain name='compute.local'/>
  <dns>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-0.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-1.ocp.andyneeb.com' port='2380' weight='10'/>
    <srv service='etcd-server-ssl' protocol='tcp' domain='ocp.andyneeb.com' target='etcd-2.ocp.andyneeb.com' port='2380' weight='10'/>
    <host ip='192.168.50.2'>
      <hostname>bootstrap.compute.local</hostname>
    </host>
    <host ip='192.168.50.1'>
      <hostname>api-int.ocp.andyneeb.com</hostname>
      <hostname>api.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.10'>
      <hostname>master-0.compute.local</hostname>
      <hostname>etcd-0.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.11'>
      <hostname>master-1.compute.local</hostname>
      <hostname>etcd-1.ocp.andyneeb.com</hostname>
    </host>
    <host ip='192.168.50.12'>
      <hostname>master-2.compute.local</hostname>
      <hostname>etcd-2.ocp.andyneeb.com</hostname>
    </host>
  </dns>
  <ip address='192.168.50.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.50.10' end='192.168.50.250'/>
      <host mac='52:54:00:a8:32:02' name='bootstrap.compute.local' ip='192.168.50.2'/>
      <host mac='52:54:00:a8:32:0a' name='master-0.compute.local' ip='192.168.50.10'/>
      <host mac='52:54:00:a8:32:0b' name='master-1.compute.local' ip='192.168.50.11'/>
      <host mac='52:54:00:a8:32:0c' name='master-2.compute.local' ip='192.168.50.12'/>
      <host mac='52:54:00:a8:32:0d' name='compute-0.compute.local' ip='192.168.50.13'/>
      <host mac='52:54:00:a8:32:0e' name='compute-1.compute.local' ip='192.168.50.14'/>
      <host mac='52:54:00:a8:32:0f' name='compute-2.compute.local' ip='192.168.50.15'/>
    </dhcp>
  </ip>
</network>

**Comment by rbo** [comment]
@andyneeb please try: ```sysctl -w net.ipv4.conf.<PUBLIC INTERFACE>.forwarding=1``` to enable ip forwaring on the public interface. (I had the same problem with my new hetzner box and `sysctl -w net.ipv4.conf.enp4s0.forwarding=1` solved the problem.)

**Comment by andyneeb** [comment]
@rbo indeed ip forwarding on the public solves the vms connectivity issue (i can ping public hosts, which i couldn't before).
however the playbook or more likely installation of libvirt networks disables that behavior. so simply enabling forwarding and running install won't work as forwarding is being disabled during install 

i try to dig a little bit deeper over the weekend

**Comment by rbo** [comment]
I have exactly the same problem. Added `net.ipv4.conf.enp4s0.forwarding=1` to `/etc/sysctl.conf` run `sysctl -p` and reboot the host. Running the playbooks set `net.ipv4.conf.enp4s0.forwarding` back to `0`....

**Comment by andyneeb** [comment]
Making some progress. 
Activating the network in create-network.yml (step name: Active network {{ cluster_name }}) disables forwarding on the public interface.
So as a quick workaround I added

`- sysctl:
    name: net.ipv4.conf.enp0s31f6.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes`

which started the bootstrap process and downloading of images.

While waiting on etcd to start something (???) disabled ip forwarding again. I am pretty lost what might be the cause since at this point the playbook simply idles and waits for the api to come up.

Anyways manually enabling forwarding again did the trick, the bootstrap node picked up again and finished.

**Comment by rbo** [comment]
It looks like hetzner installimage use systemd.network and create `/etc/systemd/network/10-mainif.network` if you add `IPForward=ipv4` to the `[Network]` part it solve our problem permanently. 
My  `/etc/systemd/network/10-mainif.network` configuration:
```
### Hetzner Online GmbH installimage
[Match]
MACAddress=xxxxx

[Network]
Address=2a01:4f8:211:116::2/64
Gateway=148.251.184.1
Gateway=fe80::1
IPForward=ipv4

[Address]
Address=xxxxx
Peer=xxxxx
```

**Comment by rbo** [comment]
The code in hetzneronline/installimage is not new:
- https://github.com/hetzneronline/installimage/blob/master/network_config.functions.sh#L677
- https://github.com/hetzneronline/installimage/blob/master/network_config.functions.sh#L729

I don't know why this affects only our new hetzner server.

**Comment by tahonen** [comment]
Might be related to datacenter?

**Comment by andyneeb** [comment]
@rbo confirmed. Fixed it for me as well. Thx.

It did NOT affect my server 10 days ago. Since this repo did not change, my server did not change, Hetzner install process did not change I am suspecting a CentOS package that got updated since then.

**Comment by rbo** [comment]
I reinstall my old hetzner server with a fresh Centos 7.6 installation and indeed the `/etc/systemd/network/10-mainif.network` appear.

**Comment by rbo** [comment]
For me the problem is solved - closed.
