### ISSUE TITLE
The roles should live in separate github repos

### ISSUE THREAD

**Issue by flyemsafe** [RedHat-EMEA-SSA-Team/hetzner-ocp4#44]
I find the accompanying roles to be very useful for many other use cases and thing they should be broken out into their own repos.

The project can include an ansible.cfg that points to ansible/roles directory for the installation of roles. And there can be a requirements.yml

* Example

```
- src: https://github.com/flyemsafe/swygue-redhat-subscription.git
  version: master
```

Then the roles can be installed with:

```
ansible-galaxy install --force -r requirements.yml
```

**Comment by rbo** [comment]
Copy-paste from our email conversation:

- reusing from ansible roles is perfect and I love that. 
- For hetzner-ocp4 I like to have everything together and in our hands, I don't like to spend to much time to support various roles and different repos. The goal here is clearly to create the most value in as little time as possible. Even if that means less flexibility and more opinionated. 
- Our main job is not to support and maintain the hetzner-ocp4 stuff our job so to teach and practice OpenShift for customers/partners and hetzner-ocp4 is tool for us to achieve our goals. 

Your contribution is always highly appreciated! Copy the roles if you like and publish again as a stand-alone role. Feel free! For hetzner-ocp4 every is in one repo and less dependencies as possible. :-)
