### ISSUE TITLE
Default iptables prevents nodes to access machine config server 

### ISSUE THREAD

**Issue by tahonen** [RedHat-EMEA-SSA-Team/hetzner-ocp4#51]
In "vanilla" RHEL 7.7 where firewalld is disabled and iptables is in use, default rules prevents nodes to access bootstrap thru haproxy lb

**Comment by rbo** [comment]
Added some firewalld changes together with RHEL8 support: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/pull/75/commits/c26bfbb0298bb989183fb1921e44d3f3c3aa24f4#diff-15a9ac7e9b3c4a3a7462c41c27d6fe1f

**Comment by rbo** [comment]
Fixed rhel7 with commit: https://github.com/rbo/hetzner-ocp4/commit/9908ed086c2e1309223690a19adcf20e9e3fa746 

Will be merged with PR #75
