### ISSUE TITLE
Cloudflare missing account email for Letsencrypt

### ISSUE THREAD

**Issue by alezzandro** [RedHat-EMEA-SSA-Team/hetzner-ocp4#68]
I found an issue on Letsencript playbook, the cloudflare account email is missing and the playbook fails with an error.

Letsencrypt role search for the variable:
`le_cloudflare_account_email"`

So the best way is to define it in `ansible/roles/openshift-4-cluster/tasks/create.yml`:
`le_cloudflare_account_email: "{{ cloudflare_account_email }}"`

I'll make a PR for that

**Comment by rbo** [comment]
Please, check out Issue #49 it's basically the same.

**Comment by alezzandro** [comment]
correct but you're mentioning the check variable playbook, I solved by editing the create.yml file, anyway PR coming, please check if it could be accepted

**Comment by alezzandro** [comment]
pr merged, i'll close this issue
