### ISSUE TITLE
CoreOS images for v4.2 remote location changed

### ISSUE THREAD

**Issue by alezzandro** [RedHat-EMEA-SSA-Team/hetzner-ocp4#70]
I've experienced some issues in installing the current version (4.2).

I discovered that the remote location on openshift.com changed (`ansible/roles/openshift-4-cluster/defaults/main.yml`):
```
-coreos_download_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-{{ coreos_version }}-qemu.qcow2"
+coreos_download_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.2.0-rc.5/rhcos-{{ coreos_version }}-qemu.qcow2"
```

The /latest remote subdir now has been bumped to 4.3 version and qemu version disappeared.

We should always point to the latest stable to avoid these issues.

I'm going to create a PR.

**Comment by rbo** [comment]
Thanks for the Issue & PR! Merged & Closed.
