### ISSUE TITLE
make cluster start at boot

### ISSUE THREAD

**Issue by ikke-t** [RedHat-EMEA-SSA-Team/hetzner-ocp4#76]
At the moment cluster remains down if the host reboots. Let's fix that by either doing (pseudo code):

for all machines
  virsh autostart machine-name
done

in ansible command for list of servers,

or another way, just do

for all machines
  ln -s /etc/libvirt/qemu/autostart/ocp4-compute-0.xml /etc/libvirt/qemu/ocp4-compute-0.xml
done

both with ansible, naturally.

**Comment by rbo** [comment]
Or you run `./ansible/04-start-cluster.yml`

**Comment by tahonen** [comment]
Might be that you have multiple cluster on same servers

**Comment by ikke-t** [comment]
Ok, I didn't think of that. I never do, but sometimes the host needs to be rebooted.

**Comment by rbo** [comment]
Maybe we can add autostart to the vm

**Comment by ikke-t** [comment]
- name: set autostart for a VM
  virt:
    name: foo
    autostart: yes

**Comment by rbo** [comment]
Right, but not as default. Default should be "no" and you can change the setting in the cluster.yml for example: `vm_autostart: yes`

**Comment by rbo** [comment]
@PixelJonas provided a patch #119 - merged in devel branch.

**Comment by rbo** [comment]
Will merge into master with #122
