### ISSUE TITLE
Support more than one DNS forwarders ansible/group_vars/all:forward_dns

### ISSUE THREAD

**Issue by rbo** [RedHat-EMEA-SSA-Team/hetzner-ocp4#8]
Add support to add more than one DNS forwarders:

```
grep forward ansible/group_vars/all
# forwarder to access the internet for your prviate DNS server
forward_dns: 8.8.8.8
```
https://wiki.hetzner.de/index.php/Hetzner_Standard_Name_Server/en

**Comment by tahonen** [comment]
It is a list, so just document correct formatting .... 8.8.8.8.; 9.9.9.9;

**Comment by rbo** [comment]
Not needed anymore.
