### ISSUE TITLE
Image Registry not ready after fresh 4.3 installation

### ISSUE THREAD

**Issue by jaxx0r** [RedHat-EMEA-SSA-Team/hetzner-ocp4#82]
When installing 4.3 as baremetal installation, image registry is marked offline as no object storage is available. Fix is written in the OCP docs, would be nice to automate it as well.

Link to docs:
https://docs.openshift.com/container-platform/4.3/registry/configuring-registry-storage/configuring-registry-storage-baremetal.html#configuring-registry-storage-baremetal

Manual Fix:
"oc edit configs.imageregistry.operator.openshift.io " and change "managementState: Removed" to "managementState: Managed"

**Comment by rbo** [comment]
Fresh installation from master?

**Comment by rbo** [comment]
We change the state if nfs storage is enabled. 

https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4/pull/81/commits/caa1c40785a9840365a2b5217ea2f10eb5073621

**Comment by jaxx0r** [comment]
ah sorry - maybe my installation was not as fresh, missed that in my playbooks ... :)
