### ISSUE TITLE
Installation does not work rhcos image not available. - 4.3 installation is broken! 

### ISSUE THREAD

**Issue by LutzLange** [RedHat-EMEA-SSA-Team/hetzner-ocp4#83]
# pwd
/var/lib/libvirt/images
# cat rhcos-4.3.0.qcow2
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pub/openshift-v4/dependencies/rhcos/4.3/4.3.0/rhcos-4.3.0-x86_64-qemu.qcow2.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at mirror.openshift.com Port 443</address>
</body></html>

**Comment by tahonen** [comment]
Either someone deleted those images or they are moved. Link "Download RHCOS to create machines for your cluster to use during installation." in cloud.openshift.com points to that same dir and it has only installer and clients

**Comment by rbo** [comment]
Red Hat removed the qemu qcow from the normal release directory :-(

**Comment by rbo** [comment]
```
curl -I https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/4.3.0/rhcos-4.3.0-x86_64-qemu.qcow2.gz
HTTP/1.1 404 Not Found
Date: Fri, 14 Feb 2020 08:46:48 GMT
Server: Apache/2.2.15 (Red Hat)
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

We have to use `https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.3.0-0.nightly-2020-01-15-025207/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz`

**Comment by rbo** [comment]
# ToDo

- [ ] Change Download URL to https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.3.0-0.nightly-2020-01-15-025207/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz
- [ ] Add qcow file check for better error handling

**Comment by tahonen** [comment]
Workaround is just to modify ansible/roles/openshift-4-cluster/defaults/main.yml file. 
Change coreos_download_url to 
https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/4.3.0-0.nightly-2020-01-15-025207/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz

**Comment by rbo** [comment]
Right, or add 
`coreos_download_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/4.3.0-0.nightly-2020-01-15-025207/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz` to your cluster.yml

**Comment by rbo** [comment]
Really strange, bootstrap boots but masters not:
```
  100.767838] systemctl[1868]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
[[  100.770748] systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
FAILED] Failed to start Switch Root.
See 'systemctl s[  100.774920] systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
```

**Comment by rbo** [comment]
my weird, installation with:
```
coreos_version: 43.81.202001142154.0
coreos_download_url: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.3.0-0.nightly-2020-01-15-025207/rhcos-43.81.202001142154.0-qemu.x86_64.qcow2.gz"
``` 
works very well.
