### ISSUE TITLE
possibility to add new worker nodes

### ISSUE THREAD

**Issue by lucamaf** [RedHat-EMEA-SSA-Team/hetzner-ocp4#88]
Would be nice to have an ansible role (with parameters) to add new worker nodes to the cluster

**Comment by rbo** [comment]
Added `./ansible/add-node.yml` - works very well.

Problem: New nodes ignored in:
- `./ansible/03-stop-cluster.yml`
- `./ansible/04-start-cluster.yml`
- `./ansible/99-destroy-cluster.yml`

**Comment by rbo** [comment]
Working branch Issue88

**Comment by rbo** [comment]
Force update (rebase devel)

**Comment by rbo** [comment]
Branch Issue88 delete. 

PR with the feature is welcome. Unfortunately, I don't have time and the need to implement it. 

Feel free to reopen the issue if you have any questions or complaints. 

Thanks
